/*
 * ==========================================================================
 * SAP CPI Groovy Script  —  Message 1: ShipmentSet (XML) -> CarrierWaybill (JSON)
 * ==========================================================================
 * Replaces the graphical Message Mapping step.
 *
 * Source : ShipmentSet.xsd            (ShipmentSet -> Shipment[])
 * Target : CarrierWaybill OpenAPI     (CarrierWaybillRequest { carrierId, waybill })
 *
 * Mapping reference: "Message 1" tab, SAP_Electrolit - Cedar ARMS workbook.
 * Tags used there:
 *   Direct         = copied as-is from SAP
 *   Transform      = looked up / converted / restructured from SAP
 *   Template       = static ELECTROLIT ARMS default, applied by Cedar itself
 *                    downstream -> NOT sent by this script (omitted from output)
 *   ARMS-completed = filled in later by Waco/ARMS -> NOT produced here
 *   ARMS-generated = generated by ARMS -> NOT produced here
 *
 * carrierId is read from the Exchange Property named by CARRIER_ID_PROPERTY
 * below. Set that property upstream in a Content Modifier before this script.
 *
 * Behaviour:
 *   - If the payload root is <ShipmentSet> with multiple <Shipment> elements,
 *     this produces a JSON ARRAY of CarrierWaybillRequest objects (one per
 *     Shipment/railcar, per the "1 outbound delivery = 1 railcar" rule).
 *   - If the payload root is a single <Shipment> (e.g. you already split
 *     upstream with a Splitter), it produces a single JSON OBJECT.
 *   Since the target endpoint (/waybills) takes one request per call, if you
 *   keep multiple Shipments together you'll still need a Splitter AFTER this
 *   script (General Splitter on the JSON array) before the receiver call.
 *
 * Items marked "TODO" below are fields the workbook's Decision List/Decisions 2
 * tabs flag as still needing real master-data lookups (SPLC/FSAC master,
 * ARMS location IDs, template ID, etc.). Hardcoded placeholders are used so
 * the script runs end-to-end; replace them with real lookups (Value Mapping,
 * Data Store, or a lookup API call) once Cedar/LeverX confirm the values.
 * ==========================================================================
 */

import com.sap.gateway.ip.core.customdev.util.Message
import groovy.json.JsonOutput
import groovy.transform.Field
import groovy.util.XmlSlurper

// --------------------------------------------------------------------------
// CONSTANTS
// --------------------------------------------------------------------------
// Name of the Exchange Property that carries carrierId. Set it upstream in a
// Content Modifier (Exchange Property, not Header) before this script step.
@Field final String CARRIER_ID_PROPERTY = 'CarrierId'

// Still needed even though it's not a "Template" row: descriptions[].commodityCode
// and the header commodityCode are tagged Transform (material-master derived),
// not Template, so they stay. Value per PA-00618241-1 pending real STCC lookup.
@Field final String COMMODITY_CODE = '2086130'

// TODO — confirm with Cedar/LeverX (see "Decision list" / "Decisions 2" tabs)
@Field final String  ORIGIN_FSAC          = null   // Plant 1280 / WARL -> Cedar location/SPLC master
@Field final Integer SHIPPER_LOCATION_ID  = null   // Plant 1280 -> ARMS shipper location id

// LBS (PZA or CV) -> rail weight-unit code. Only LBS->L is confirmed; extend as Electrolit confirms others.
@Field final Map WEIGHT_UOM_MAP = [
    'LBS': 'L'
]
// CA -> ARMS packaging form code. Placeholder pass-through until Cedar confirms the actual code.
@Field final Map PACKAGING_UOM_MAP = [
    'CA': 'CA'   // TODO confirm actual ARMS/rail packaging code for "cases"
]

Message processData(Message message) {
    def bodyText = message.getBody(String) as String
    def root = new XmlSlurper().parseText(bodyText)

    // carrierId comes from an Exchange Property set upstream (Content Modifier),
    // not from the payload — the workbook mapping doesn't cover this field at all.
    def carrierId = toInteger(message.getProperty(CARRIER_ID_PROPERTY)?.toString())

    // Accept either <ShipmentSet><Shipment>...</Shipment></ShipmentSet> or a bare <Shipment>
    def shipments = (root.name() == 'ShipmentSet') ? root.Shipment : [root]

    def requests = shipments.collect { shipment -> buildCarrierWaybillRequest(shipment, carrierId) }

    def outputBody = (requests.size() == 1) ? requests[0] : requests
    message.setBody(JsonOutput.toJson(outputBody))
    message.setHeader('Content-Type', 'application/json')
    return message
}

// ==========================================================================
// Top-level assembly
// ==========================================================================

Map buildCarrierWaybillRequest(def shipment, Integer carrierId) {
    return [
        carrierId: carrierId,            // from Exchange Property — see CARRIER_ID_PROPERTY
        waybill  : buildWaybill(shipment)
    ]
}

Map buildWaybill(def shipment) {
    def stopsList      = shipment.Stops.Stops
    def originStop      = findStop(stopsList, 'ORIG') ?: firstBySequence(stopsList)
    def destinationStop = findStop(stopsList, 'DEST') ?: lastBySequence(stopsList)
    def destAddress      = destinationStop?.Location?.Location?.Address?.Address

    def deliveryNumber = findReferenceValue(shipment, ['DELIVERY NUMBER', 'PRIMARY REFERENCE']) \
                          ?: textOrNull(shipment.DeliveryNumber)

    def totalWeightLbs = sumLineItemWeightLbs(shipment)
    def netWeightTons  = (totalWeightLbs != null) \
                          ? (totalWeightLbs / 2000G).setScale(3, BigDecimal.ROUND_HALF_UP) \
                          : null

    return [
        // --- Correlation / references --------------------------------------------------
        billOfLadingNumber   : deliveryNumber,                                   // Direct: References[DELIVERY NUMBER] or [PRIMARY REFERENCE]
        shipmentId           : deliveryNumber,                                   // Direct: same as delivery number
        extendedReferenceInfo: buildExtendedReferenceInfo(shipment),             // Transform: References[] + SupportInfos[]

        // --- Commodity / weight ----------------------------------------------------------
        commodityCode  : COMMODITY_CODE,                                        // Transform: material master STCC (pending real lookup)
        netWeightTons  : netWeightTons,                                         // Transform: sum(lineItems.weight) LBS -> tons
        weightUnitCode : mapWeightUom(firstLineItemWeightUom(shipment)),        // Transform: LBS -> L

        // NOTE: loadStatus, transportationMethod, trafficType, shipmentPaymentMethod,
        // shipmentQualifier, billingCode, capacityLoadCode, originCityName,
        // originStateOrProvince, originScac, originCarrierCode, consignorCustomerName,
        // and waybillTemplateId are all tagged "Template" in the workbook — Cedar
        // applies the ELECTROLIT ARMS default template for these, so they're
        // intentionally omitted here rather than sent by SAP.

        // --- Origin ------------------------------------------------------------------------
        originFsac: ORIGIN_FSAC,                                                // TODO: Cedar location/SPLC master lookup (Transform)

        // --- Destination -------------------------------------------------------------------
        destinationCityName       : textOrNull(destAddress?.City),              // Direct: SAP ship-to address
        destinationStateOrProvince: textOrNull(destAddress?.State),             // Direct: SAP ship-to address
        destinationFsac            : null,                                     // TODO: map customer/DC -> BNSF destination SPLC

        // --- Parties -------------------------------------------------------------------------
        consigneeCustomerName: textOrNull(destinationStop?.Location?.Location?.Name), // Direct
        consigneeLocationId  : toInteger(textOrNull(destinationStop?.Location?.Location?.Id)), // TODO: map to real ARMS location id
        shipperLocationId    : SHIPPER_LOCATION_ID,                             // TODO: Plant 1280 -> ARMS shipper location id
        parties              : buildParties(destinationStop),                  // Direct only — static Template shipper party dropped

        // --- Route / line items ----------------------------------------------------------------
        route    : [],                                                         // Cedar derives from PA lane + template; not sent from SAP
        lineItems: buildLineItems(shipment),                                   // Transform: Freights[].LineItems[]

        // --- Waybill housekeeping ----------------------------------------------------------------
        waybillDate: formatDateToIso(textOrNull(originStop?.EarliestDateTime)) // Transform: planned ship date -> ISO
        // equipmentDetails[], waybillNumber, armsTrackingId are ARMS-completed / ARMS-generated
        // and intentionally NOT sent in Message 1.
    ]
}

// ==========================================================================
// Line items  (Freights[].LineItems[] -> waybill.lineItems[])
// ==========================================================================

List buildLineItems(def shipment) {
    def items = []
    int seq = 1
    shipment.Freights.Freights.each { freight ->
        freight.LineItems.LineItems.each { li ->
            def qty          = toNumber(textOrNull(li.Quantity))
            def weight        = toNumber(textOrNull(li.Weight))
            def handlingUnit  = toNumber(textOrNull(li.HandlingUnit))
            def lineNumber    = toInteger(textOrNull(li.Id)) ?: seq

            items << [
                number     : lineNumber,                                        // Direct: LineItems.Id
                descriptions: [[
                    ladingDescription: textOrNull(li.Description),             // Direct
                    commodityCode     : COMMODITY_CODE                          // Transform: material master STCC
                    // commodityCodeQualifier ("T") is Template — omitted, Cedar applies it
                ]],
                quantity: [
                    ladingQuantity   : qty,                                     // Direct: case count
                    weight           : weight,                                  // Direct: pounds
                    weightUnitCode   : mapWeightUom(textOrNull(li.WeightUom)),  // Transform: LBS -> L
                    packagingFormCode: mapPackagingUom(textOrNull(li.QuantityUom)) // Transform: CA -> packaging code
                ],
                measurements: handlingUnit != null ? [[
                    measurementQualifier: 'PLT',                                // TODO confirm ARMS pallet qualifier code
                    measurementValue     : handlingUnit,                        // Transform: HandlingUnit as pallet count
                    codeListQualifier    : textOrNull(li.HandlingUnitUom)
                ]] : []
                // priceAuthorities[] (referenceId + issuingCarrierIdentifier) is
                // entirely Template — omitted, Cedar applies PA-00618241-1 / BNSF itself.
            ]
            seq++
        }
    }
    return items
}

// ==========================================================================
// Parties  (Direct consignee only — the shipper/freight-bill/in-care-of parties
// are tagged "Template" in the workbook and are supplied by Cedar's ARMS
// template, so they're intentionally not built here.)
// ==========================================================================

List buildParties(def destinationStop) {
    def parties = []

    // Consignee (Direct, from SAP ship-to / destination stop)
    def loc  = destinationStop?.Location?.Location
    def addr = loc?.Address?.Address
    if (loc) {
        parties << [
            name              : textOrNull(loc.Name),
            locationQualifier : 'CN',       // TODO confirm ARMS party-role code for "consignee"
            locationIdentifier: textOrNull(loc.Id),
            address           : textOrNull(addr?.Address1) ? [textOrNull(addr.Address1)] : [],
            cityName          : textOrNull(addr?.City),
            stateOrProvince   : textOrNull(addr?.State),
            postalCode        : textOrNull(addr?.Zip),
            countryCode       : textOrNull(addr?.Country)
        ]
    }
    return parties
}

// ==========================================================================
// References / support info  ->  extendedReferenceInfo[]
// ==========================================================================

/** Flattens References + SupportInfos across ALL Freights of one Shipment. */
List buildExtendedReferenceInfo(def shipment) {
    def result = []
    shipment.Freights.Freights.each { freight ->
        freight.References.References.each { ref ->
            result << [
                referenceIdQualifier: 'REF',
                referenceId         : textOrNull(ref.Value),
                description         : textOrNull(ref.Name)
            ]
        }
        freight.SupportInfos.SupportInfos.each { info ->
            result << [
                referenceIdQualifier: 'SUP',
                referenceId         : textOrNull(info.Value),
                description         : textOrNull(info.Name)
            ]
        }
    }
    return result
}

/**
 * Searches References across ALL Freights of a Shipment (in document order)
 * for the first Name matching any of candidateNames (case-insensitive), and
 * returns its Value. This is the piece that replaces the original graphical
 * UDF for billOfLadingNumber.
 */
String findReferenceValue(def shipment, List<String> candidateNames) {
    for (freight in shipment.Freights.Freights) {
        for (ref in freight.References.References) {
            def name = textOrNull(ref.Name)?.trim()
            if (name && candidateNames.any { it.equalsIgnoreCase(name) }) {
                return textOrNull(ref.Value)
            }
        }
    }
    return null
}

// ==========================================================================
// Weight helpers
// ==========================================================================

BigDecimal sumLineItemWeightLbs(def shipment) {
    BigDecimal total = 0
    boolean found = false
    shipment.Freights.Freights.each { freight ->
        freight.LineItems.LineItems.each { li ->
            def n = toNumber(textOrNull(li.Weight))
            if (n != null) {
                total += n
                found = true
            }
        }
    }
    return found ? total : null
}

/** Grabs the weight UOM off the first line item found, for the header-level weightUnitCode. */
String firstLineItemWeightUom(def shipment) {
    for (freight in shipment.Freights.Freights) {
        for (li in freight.LineItems.LineItems) {
            def uom = textOrNull(li.WeightUom)
            if (uom) return uom
        }
    }
    return null
}

String mapWeightUom(String src) {
    if (!src) return null
    def key = src.trim().toUpperCase()
    return WEIGHT_UOM_MAP.containsKey(key) ? WEIGHT_UOM_MAP[key] : src
}

String mapPackagingUom(String src) {
    if (!src) return null
    def key = src.trim().toUpperCase()
    return PACKAGING_UOM_MAP.containsKey(key) ? PACKAGING_UOM_MAP[key] : src
}

// ==========================================================================
// Stop helpers
// ==========================================================================

def findStop(def stopsList, String typeContains) {
    return stopsList.find { textOrNull(it.Type)?.toUpperCase()?.contains(typeContains) }
}

def firstBySequence(def stopsList) {
    if (!stopsList || stopsList.size() == 0) return null
    return stopsList.min { toInteger(textOrNull(it.SequenceNumber)) ?: 0 }
}

def lastBySequence(def stopsList) {
    if (!stopsList || stopsList.size() == 0) return null
    return stopsList.max { toInteger(textOrNull(it.SequenceNumber)) ?: 0 }
}

// ==========================================================================
// Generic parsing helpers
// ==========================================================================

String textOrNull(node) {
    if (node == null) return null
    def t = node.text()
    return (t == null || t.trim().isEmpty()) ? null : t.trim()
}

BigDecimal toNumber(String s) {
    if (!s) return null
    try {
        return new BigDecimal(s.trim())
    } catch (Exception ignored) {
        return null
    }
}

Integer toInteger(String s) {
    if (!s) return null
    try {
        return new BigDecimal(s.trim()).intValue()
    } catch (Exception ignored) {
        return null
    }
}

/** Best-effort date normalizer; falls back to the raw string if unrecognized. */
String formatDateToIso(String raw) {
    if (!raw) return null
    def value = raw.trim()
    def patterns = ['yyyyMMdd', "yyyy-MM-dd'T'HH:mm:ss", 'yyyy-MM-dd', 'MM/dd/yyyy']
    for (p in patterns) {
        try {
            def date = Date.parse(p, value)
            return date.format('yyyy-MM-dd')
        } catch (Exception ignored) {
            // try next pattern
        }
    }
    return value
}